sudo: true
language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

install:
  - export NODE_ENV=dev
  - npm install

after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'

before_deploy:
  - npm run docs
deploy:
  - provider: pages
    skip-cleanup: true
    local_dir: docs/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
